### ISSUE TITLE
overspecificity in state view giving false negatives

### ISSUE THREAD

**Issue by akiarie** [xr0-org/xr0#53]
```C
#include <stdlib.h>

void
f() ~ [ return malloc(1); ]
{
	void *p;

	p = malloc(1);
	free(p);
	p = malloc(1);
	return p;
}
```

This is currently rejected on account of the second-allocation appearing as `heap:1`, whereas the one in the abstract is `heap:0`. There are many other ways to trigger this kind of issue. More succinctly:

```C
#include <stdlib.h>

void
f() ~ [ return malloc(1); ]
{
	free(malloc(1));
	return malloc(1);
}
```

**Comment by claude-betz** [comment]
Agree with not going with the first.

The second makes sense. So an update that runs on the axiomatic `free` and goes through every `value` in every `object` and `block`.. seems a bit involved.
